version: '3'
services:
  jupyter_flow:
    image: tensorflow/tensorflow:latest-py3-jupyter
    # build: docker/jupyter
    ports:
      - '8888:8888'
    volumes:
      - .:/tf

  pg_serv:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
